### ISSUE TITLE
[Suggestion] Add Back/Cancel button

### ISSUE THREAD

**Issue by AmeerReal** [AlexPads/ShopUI-FormAPI-Working#14]
You need to add back button in the main shop menu and in the categories menus, and you need to add cancel button in the Buy/Sell menu.

**Comment by AlexPads** [comment]
Thank you For your Suggestion! This is being worked on Along with Enchants!

**Comment by AlexPads** [comment]
@AmeerReal I am currently Rewriting the Entire Plugin So please Wait for the Revamp it will have more Features in the mean time I will keep this one up to date with API changes.

**Comment by AlexPads** [comment]
@AmeerReal Fixed in New Update! Thank you for  Waiting!
