### ISSUE TITLE
The new version is full of bugs.

### ISSUE THREAD

**Issue by SchdowNVIDIA** [AlexPads/ShopUI-FormAPI-Working#16]
Well there are so many bugs in the new version.
1:
![image](https://user-images.githubusercontent.com/39440218/52916954-e147f600-32e5-11e9-9b29-5ef5a4317918.png)
2 i can't even see what i get for selling/buying:
![image](https://user-images.githubusercontent.com/39440218/52916962-f3299900-32e5-11e9-88bc-ea8ece487692.png)
![image](https://user-images.githubusercontent.com/39440218/52916966-00468800-32e6-11e9-8085-32b25c202e33.png)
3: Default textures are bugging.
![image](https://user-images.githubusercontent.com/39440218/52916979-10f6fe00-32e6-11e9-892f-e7b6c73c7113.png)
4: No matching prices
![image](https://user-images.githubusercontent.com/39440218/52916986-2409ce00-32e6-11e9-8de0-5b0e3863eb00.png)

![image](https://user-images.githubusercontent.com/39440218/52916988-2bc97280-32e6-11e9-9250-2e8afee18a47.png)

**Comment by AlexPads** [comment]
Thank-you! i will remove my review on your plugin now :) 

They are all fixed in 3.5.2! you can check the dev section so you don;t have to wait for poggit.

**Comment by SchdowNVIDIA** [comment]
There you go. You've fixed it. There is just one mistake/bug left: 
I can't see how much do i get for selling:
![image](https://user-images.githubusercontent.com/39440218/52917365-d80d5800-32ea-11e9-8b85-58b3d5aaa39a.png)

**Comment by SchdowNVIDIA** [comment]
Okay, i delete my rating now too. and rewrite when the new version is released.

**Comment by AlexPads** [comment]
Yeah
That i can't fix bc forms can't Live update and i was alredy trying and i asked joejoe77777 and he said it wasnt possible :( im working on a way

**Comment by AlexPads** [comment]
For now though i think you will be fine :)

**Comment by AlexPads** [comment]
@SchdowNVIDIA

**Comment by SchdowNVIDIA** [comment]
Well you could add that sell/buy thing from the old version until this is fixed

**Comment by SchdowNVIDIA** [comment]
I mean it looks a bit strange only seeing the buy value. or just add another text with how much do you want to sell for blah$

**Comment by AlexPads** [comment]
I think i have a Fix one sec :)

**Comment by SchdowNVIDIA** [comment]
Okay, nice :)

**Comment by AlexPads** [comment]
@SchdowNVIDIA There u go :)

**Comment by AlexPads** [comment]
added {sell} to 2 different places.

**Comment by SchdowNVIDIA** [comment]
Nice!

**Comment by AlexPads** [comment]
If you ever want any more things just Say im Always here to fix it ASAP. (as you could see xD) 👍

**Comment by AlexPads** [comment]
am i good to close this for now? lol

**Comment by SchdowNVIDIA** [comment]
Yes, i'm rating your plugin when 3.5.3 is out with 5 stars :)
Thanks for fixing that!

**Comment by AlexPads** [comment]
You're Welcome! Thanks for the Help~!
