### ISSUE TITLE
Commands does not work

### ISSUE THREAD

**Issue by SchdowNVIDIA** [AlexPads/ShopUI-FormAPI-Working#17]
Well i've added the commands: in my shop.yml but it isn't working.

Ingame:
![image](https://user-images.githubusercontent.com/39440218/52917886-8071eb00-32f0-11e9-975a-acb22fe8243a.png)
Shop.yml (it isn't showing)
![image](https://user-images.githubusercontent.com/39440218/52917890-92538e00-32f0-11e9-8688-00608f3959ca.png)

**Comment by AlexPads** [comment]
@SchdowNVIDIA Where it says Commands should still say Items 👍 That will fix your issue 

You do NOT put Commands: above them it shoud only say items 


so Exactly what you have is fine just Move it under where it says Items: Thanks!

**Comment by SchdowNVIDIA** [comment]
Well there is no pay process.
1. There is no price (that 100$ is the name)
![image](https://user-images.githubusercontent.com/39440218/52954196-d646a180-3389-11e9-84d8-3578459d6867.png)
2. My money does not gets reduced:
![image](https://user-images.githubusercontent.com/39440218/52954232-f24a4300-3389-11e9-9a5f-fbc474b6cdb9.png)
![image](https://user-images.githubusercontent.com/39440218/52954270-fe360500-3389-11e9-995c-dc96d00aadb0.png)
![image](https://user-images.githubusercontent.com/39440218/52954287-0c842100-338a-11e9-9fb0-02b0d0fc37f8.png)

**Comment by AlexPads** [comment]
Alright Will fix when I get home from School. Because the Github Editor SUCKS 😂 @SchdowNVIDIA

**Comment by SchdowNVIDIA** [comment]
Haha yeah :D

**Comment by AlexPads** [comment]
But I do know what is wrong rn 😂 Casually Forgot a part xD

**Comment by SchdowNVIDIA** [comment]
A part hm :P

**Comment by AlexPads** [comment]
Yeah 1 or 10 parts 😂

**Comment by AlexPads** [comment]
I rewrote the entire plugin in 3 days I didn't expect it to be perfect. 😂 👍

**Comment by SchdowNVIDIA** [comment]
Lol okay

**Comment by AlexPads** [comment]
@SchdowNVIDIA Would you Like to work together on plugins? I see you have made plugins it would be really helpful to have someone else that is able to help me because Right now I only have 3 others that are all beginners and don't really try and do anything. 😢 🥇

**Comment by AlexPads** [comment]
Also its 1:50Pm where I live rn and I don't get off school until 5pm and won't be home until 5:45pm becuase I am auditorium manager and have a show after school to run.

**Comment by SchdowNVIDIA** [comment]
For requests like that contact me via discord Schdow#6718

**Comment by AlexPads** [comment]
@SchdowNVIDIA Fixed in Latest Update!
