### ISSUE TITLE
You can buy commands without having enough money + suggestion

### ISSUE THREAD

**Issue by SchdowNVIDIA** [AlexPads/ShopUI-FormAPI-Working#18]
Well, I've tried to buy a command without having enough money and it worked.
Here:
![image](https://user-images.githubusercontent.com/39440218/53107639-b653e100-3535-11e9-8bbd-4780de07fea7.png)
Then:
![image](https://user-images.githubusercontent.com/39440218/53107660-c4096680-3535-11e9-83d1-2f9a182f4493.png)
End: 
![image](https://user-images.githubusercontent.com/39440218/53107674-ce2b6500-3535-11e9-9880-1bc7f15d6f2d.png)

**Comment by SchdowNVIDIA** [comment]
Oh and my suggestion is to add a little "would you really like to buy that command" form.

**Comment by AlexPads** [comment]
OK I will fix the money part and then add the form in the next approved
update :) that way I don't have to try and get it approved for such a small
update .

**Comment by AlexPads** [comment]
The Money will be fixed in the next dev build.
