### ISSUE TITLE
Internal Server Error when changing Name from Default [Bug]

### ISSUE THREAD

**Issue by CryptoKey98** [AlexPads/ShopUI-FormAPI-Working#21]
I've decided to open a thread because the issue still persists after the update, 

I can't change the name or else it returns an internal server error.

> `[Server thread/CRITICAL]: ErrorException: "Undefined offset: 5" (EXCEPTION) in "plugins/ShopUI-FormAPI-Working.phar/src/SaltyPixelDevz/CustomShopUIv2/Shop" at line 279`

For example:

`"35:1:64:25:1.75:Orange Wool:textures/blocks/wool_colored_orange"` would return an error.

I can't use default for colored wool because the default will always be white wool.

I've tired using quotes: "Orange Wool". No good.
I've tried no spaces: OrangeWool. No good.

Side Note: Tried to join your discord server but link is expired/invalid.

**Comment by CryptoKey98** [comment]
Here's a GIF of the error demonstrated (larger than 10 MB can't upload here): https://imgur.com/1u81Bnv

**Comment by CryptoKey98** [comment]
Update: So with the newest update, it now displays the correct name for colored wool in the shop menu but it says on the top left that you bought white wool.

**Comment by AlexPads** [comment]
Reeeeeeeeeeeee

**Comment by AlexPads** [comment]
Try the Latest Dev Build Tell me If it works @CryptoKey98

**Comment by CryptoKey98** [comment]
Can confirm that the new update works.

**Comment by AlexPads** [comment]
Thanks!
