### ISSUE TITLE
[Suggestion] Permission Nodes and MultiShop Support!

### ISSUE THREAD

**Issue by CryptoKey98** [AlexPads/ShopUI-FormAPI-Working#22]
Just a suggestion. ¯\\_(ツ)_/¯ Would be nice if shop was accessible to only certain ranks/groups.

**Comment by AlexPads** [comment]
I am currently working on this Feature. :)

**Comment by CryptoKey98** [comment]
Also have another suggestion. Can you make shop types? Like for example: Shop, vipShop, etc...

**Comment by AlexPads** [comment]
I will update the config to allow like the /shop vip and /shop and /shop starter stuff like that where you can enable and disable the categories the config will update making it have 
Example:

Shop:
 0:
    Name: ""
    Items: 
      - ""
Vip #used with /shop vip
 0:
 etc.... 
and each one will have permissions for each also I will make permissions for each shop like 

shop.vip.blocks to only see the blocks section in shop and other parts like that but don't expect this update quickly. I will probably do it in small increments.

**Comment by CryptoKey98** [comment]
That's awesome. Thanks for your continued efforts in making an already 5/5 plugin.

**Comment by AlexPads** [comment]
You're very Welcome Kind Sir 👍

**Comment by AlexPads** [comment]
But really though you don't understand the amount of people that get really angry when things are not perfect and make really angry remarks and expect me to have it fixed in 3.5 seconds. and also leave 1 Star reviews on poggit saying its broken when in reality they just don't understand how to edit the shop file 👎  So Thank you! 👍

**Comment by CryptoKey98** [comment]
Yeah actually so those nasty reviews. Literally half of them weren't your fault and just their ignorance. 

I left you a review that you deserve.

**Comment by AlexPads** [comment]
Thank you! really helps out 👍

**Comment by AlexPads** [comment]
Will try to have the New Features out in 2-3 Weeks because I am Busy with school right now.

**Comment by AlexPads** [comment]
Updated the Time stamp on the New features release 😉 ❤️
