### ISSUE TITLE
[Bug] Setting the "Thanks" option in config to "false" causes error

### ISSUE THREAD

**Issue by CryptoKey98** [AlexPads/ShopUI-FormAPI-Working#23]
So if you have this option set to false, closing the shop will create an internal server error.

```[Server thread/CRITICAL]: ErrorException: "Undefined index:" (EXCEPTION) in "plugins/ShopUI-FormAPI-Working_dev-64.phar/src/SaltyPixelDevz/CustomShopUIv2/Shop" at line 165```

![capture](https://user-images.githubusercontent.com/30509839/53799413-8cb49580-3ef7-11e9-8a20-6f37c8f6e988.PNG)

**Comment by CryptoKey98** [comment]
Demonstration of Error: https://youtu.be/0d_EQ6OQGoA

**Comment by AlexPads** [comment]
Then Leave it true for now I will fix that in the future update with
permissions.

**Comment by CryptoKey98** [comment]
@AlexPads Oh of course. Just wanted to let you know of the issue. 👍

**Comment by AlexPads** [comment]
You could also just set that message to a Blank "" like that if you really
don't want the message rn
