### ISSUE TITLE
[Suggestion] Allow the option to disable/enable Buy & Sell for certain items

### ISSUE THREAD

**Issue by CryptoKey98** [AlexPads/ShopUI-FormAPI-Working#24]
I think it would be nice to choose what items you can sell or buy. 💯

**Comment by AlexPads** [comment]
Ok will also add this!

**Comment by AlexPads** [comment]
Not done with this Yet but Permissions and Unlimited Shops are online in the Dev Sections if you would like to test!

**Comment by AlexPads** [comment]
i'm not going to add this for a while probably but Thank you for the Suggestion!

**Comment by CryptoKey98** [comment]
I see, I'll test them out and let you know of any possible bugs. :) Awesome.
