### ISSUE TITLE
[Suggestion] Add subcategories and a search-bar

### ISSUE THREAD

**Issue by CryptoKey98** [AlexPads/ShopUI-FormAPI-Working#27]
CryptoKey back again with his suggestions. Haha

So what I mean with subcategories for example;

`0:`
   ` Name: "Nature:textures/blocks/grass_side_carried"`
   ` Subs:  # use '[ ]' if no subcategories.`
      ` - "0:Dirt:textures/blocks/dirt" # ID:Name:Picture`
      ` - "1:Wood:textures/blocks/log_oak"`

 `Items:`
```
            0:

                 - "3:0:64:5:1:Default:textures/blocks/dirt"
                 - "3:1:64:5:1:Default:textures/blocks/coarse_dirt"
                 - "2:0:64:5:1:Default:textures/blocks/grass_side_carried"
                 - "243:0:64:10:1:Default:textures/blocks/dirt_podzol_side"
                 - "110:0:64:12:1:Default:textures/blocks/mycelium_side"
```
```
             1:   

                 - "17:0:64:12:2:Default:textures/blocks/log_oak"
                 - "162:1:64:12:2:Default:textures/blocks/log_big_oak"
                 - "17:1:64:12:2:Default:textures/blocks/log_spruce"
                 - "17:2:64:12:2:Default:textures/blocks/log_birch"
                 - "162:0:64:12:2:Default:textures/blocks/log_jungle"
```
`1:`       
`....`

Also a search-bar if that's even possible in FormAPI. Thanks for reading. 👍

**Comment by AlexPads** [comment]
I'll work on it but it won't come fast

**Comment by CryptoKey98** [comment]
That's not an issue at all. Thanks for responding. :)

**Comment by AlexPads** [comment]
Thank you for your Great Suggestions! Love them! All is fixed please report bug because no matter how hard i test it there are always bugs
