### ISSUE TITLE
Nothing happen when item bought

### ISSUE THREAD

**Issue by FaanMaario** [AlexPads/ShopUI-FormAPI-Working#28]
Hi,
When you buy/sell something, it doesn't do anything and I don't know why.

-----------

```
 0:
    Name: "Armes:textures/items/stone_sword"
    Items:
      - "261:0:1:500:0:Default:textures/items/bow_standby"
  1:
    Name: "Blocs:textures/blocks/dirt"
    Items:
      - "4:0:64:50:2:Default:textures/blocks/cobblestone"
      - "3:0:64:10:1:Default:textures/blocks/dirt"
      - "1:0:64:12:.5:Default:textures/blocks/stone"
      - "17:0:64:12:2:Default:textures/blocks/log_oak"
      - "17:1:64:12:2:Default:textures/blocks/log_spruce"
      - "17:2:64:12:2:Default:textures/blocks/log_birch"
      - "17:3:64:12:2:Default:textures/blocks/log_jungle"
      - "162:0:64:20:2:Default:textures/blocks/log_acacia"
      - "162:1:64:20:2:Default:textures/blocks/log_big_oak"
      - "20:0:64:25:2:Default:textures/blocks/glass"
      - "24:0:64:50:2:Default:textures/blocks/sandstone_normal"
      - "98:0:64:50:2:Default:textures/blocks/stonebrick"
      - "155:0:64:75:2:Default:textures/blocks/quartz_block_side"
      - "88:0:64:30:0.5:Default:textures/blocks/snow"
      - "44:0:64:75:3:Default:textures/blocks/stone_slab_side"
      - "47:0:64:50:2:Default:textures/blocks/bookshelf"
      - "45:0:64:50:2:Default:textures/blocks/brick"
      - "87:0:64:150:1:Default:textures/blocks/nether_brick"
  2:
    Name: "Nourriture:textures/items/apple"
    Items:
      - "466:0:1:18000:0:Default:http://saltypixel.ga/textures/items/enchanted_golden_apple.png"
      - "322:0:1:1500:0:Default:textures/items/apple_golden"
      - "364:0:16:5:1:Default:textures/items/beef_cooked"
      - "320:0:16:6:1:Default:textures/items/porkchop_cooked"
      - "424:0:16:5:1:Default:textures/items/mutton_cooked"
  3:
    Name: "Agriculture:textures/items/stone_hoe"
    Items:
      - "291:0:1:100:1:Default:textures/items/stone_hoe"
      - "351:15:32:50:1.75:Default:/textures/items/inc_sac"
      - "296:0:12:50:2.50:Default:textures/items/seeds_wheat"
      - "338:0:32:50:2:Default:textures/items/sugar_cane"
      - "362:0:32:50:1.50:Default:textures/items/seeds_melon"
      - "360:0:1:10:1:Default:textures/items/melon"
      - "361:0:32:50:2:Default:textures/items/seeds_pumpkin"
      - "391:0:32:50:1:Default:textures/items/carrot"
      - "392:0:32:50:1:Default:textures/items/potato"
  4:
    Name: "Musique:textures/blocks/jukebox_top"
    Items:
      - "84:0:1:50000:0:Default:textures/blocks/jukebox_top"
      - "501:0:1:5000:0:Skrillex - Bangarang:textures/items/record_cat"
      - "500:0:1:5000:0:Petit biscuit - Sunset Lover:textures/items/record_13"
      - "503:0:1:5000:0:Alan walker - Fade:textures/items/record_chirp"
      - "504:0:1:5000:0:Tobu - Hope:textures/items/record_far"
      - "505:0:1:5000:0:Manuel - GAS GAS GAS:textures/items/record_mall"
      - "506:0:1:5000:0:Default:textures/items/record_mellohi"
      - "507:0:1:5000:0:Default:textures/items/record_stal"
      - "508:0:1:5000:0:Default:textures/items/record_strad"
      - "509:0:1:5000:0:Default:textures/items/record_ward"
      - "510:0:1:5000:0:OMFG - HELLO:textures/items/record_11"
      - "511:0:1:5000:0:Default:textures/items/record_wait"
  5:
    Name: "Minerais:textures/items/diamond"
    Items:
      - "264:0:1:350:150:Default:textures/items/diamond"
      - "265:0:1:250:100:Default:textures/items/iron_ingot"
      - "266:0:1:275:60:Default:textures/items/gold_ingot"
      - "388:0:1:400:200:Default:textures/items/emerald"
      - "263:0:1:25:1.75:Default:textures/items/coal"
      - "351:4:1:25:10:Default:textures/items/lapis_lazuli"
      - "331:0:1:25:5:Default:textures/items/redstone"
  6:
    Name: "Spawners et Loots:textures/blocks/mob_spawner"
    Items:
      - "52:0:1:1000:100:Default:textures/blocks/mob_spawner"
      - "383:34:1:50000:100:Default:textures/items/egg_skeleton"
      - "383:35:1:75000:100:Default:textures/items/egg_spider"
      - "383:43:1:150000:100:Default:textures/items/egg_blaze"
      - "383:36:1:250000:100:Default:textures/items/egg_pigzombie"
      - "383:33:1:300000:100:Default:textures/items/egg_creeper"
      - "383:20:1:400000:100:Default:textures/items/egg"
      - "369:0:64:500:50:Default:textures/items/blaze_rod"
      - "352:0:64:50:3.5:Default:textures/items/bone"
      - "262:0:64:50:2.5:Default:textures/items/arrow"
      - "287:0:64:50:4:Default:textures/items/string"
      - "375:0:64:10:3:Default:textures/items/spider_eye"
      - "371:0:64:50:5:Default:textures/items/gold_nugget"
      - "288:0:64:10:5:Default:textures/items/feather"
      - "334:0:64:10:5:Default:textures/items/leather"
      - "367:0:1:10:10:Default:textures/items/rotten_flesh"
  7:
    Name: "Argile:textures/blocks/hardened_clay"
    Items:
      - "172:0:64:15:3:Default:textures/blocks/hardened_clay"
      - "159:0:64:20:4:Default:textures/blocks/hardened_clay_stained_white"
      - "159:1:64:20:4:Default:textures/blocks/hardened_clay_stained_orange"
      - "159:2:64:20:4:Default:textures/blocks/hardened_clay_stained_magenta"
      - "159:3:64:20:4:Default:textures/blocks/hardened_clay_stained_light_blue"
      - "159:4:64:20:4:Default:textures/blocks/hardened_clay_stained_yellow"
      - "159:5:64:20:4:Default:textures/blocks/hardened_clay_stained_lime"
      - "159:6:64:20:4:Default:textures/blocks/hardened_clay_stained_pink"
      - "159:7:64:20:4:Default:textures/blocks/hardened_clay_stained_gray"
      - "159:8:64:20:4:Default:textures/blocks/hardened_clay_stained_silver"
      - "159:9:64:20:4:Default:textures/blocks/hardened_clay_stained_cyan"
      - "159:10:64:20:4:Default:textures/blocks/hardened_clay_stained_purple"
      - "159:11:64:20:4:Default:textures/blocks/hardened_clay_stained_blue"
      - "159:12:64:20:4:Default:textures/blocks/hardened_clay_stained_brown"
      - "159:13:64:20:4:Default:textures/blocks/hardened_clay_stained_green"
      - "159:14:64:20:4:Default:textures/blocks/hardened_clay_stained_red"
      - "159:15:64:20:4:Default:textures/blocks/hardened_clay_stained_black"
  8:
    Name: "Béton:textures/blocks/concrete"
    Items:
      - "237:0:64:20:4:Default:textures/blocks/concrete_powder_white"
      - "237:1:64:20:4:Default:textures/blocks/concrete_powder_orange"
      - "237:2:64:20:4:Default:textures/blocks/concrete_powder_magenta"
      - "237:3:64:20:4:Default:textures/blocks/concrete_powder_light_blue"
      - "237:4:64:20:4:Default:textures/blocks/concrete_powder_yellow"
      - "237:5:64:20:4:Default:textures/blocks/concrete_powder_lime"
      - "237:6:64:20:4:Default:textures/blocks/concrete_powder_pink"
      - "237:7:64:20:4:Default:textures/blocks/concrete_powder_gray"
      - "237:8:64:20:4:Default:textures/blocks/concrete_powder_silver"
      - "237:9:64:20:4:Default:textures/blocks/concrete_powder_cyan"
      - "237:10:64:20:4:Default:textures/blocks/concrete_powder_purple"
      - "237:11:64:20:4:Default:textures/blocks/concrete_powder_blue"
      - "237:12:64:20:4:Default:textures/blocks/concrete_powder_brown"
      - "237:13:64:20:4:Default:textures/blocks/concrete_powder_green"
      - "237:14:64:20:4:Default:textures/blocks/concrete_powder_red"
      - "237:15:64:20:4:Default:textures/blocks/concrete_powder_black"
```

**Comment by LeoBdt** [comment]
> Hi,
> When you buy/sell something, it doesn't do anything and I don't know why.
> 
> 0:
> Name: "Armes:textures/items/stone_sword"
> Items:
> - "261:0:1:500:0:Default:textures/items/bow_standby"
> 1:
> Name: "Blocs:textures/blocks/dirt"
> Items:
> - "4:0:64:50:2:Default:textures/blocks/cobblestone"
> - "3:0:64:10:1:Default:textures/blocks/dirt"
> - "1:0:64:12:.5:Default:textures/blocks/stone"
> - "17:0:64:12:2:Default:textures/blocks/log_oak"
> - "17:1:64:12:2:Default:textures/blocks/log_spruce"
> - "17:2:64:12:2:Default:textures/blocks/log_birch"
> - "17:3:64:12:2:Default:textures/blocks/log_jungle"
> - "162:0:64:20:2:Default:textures/blocks/log_acacia"
> - "162:1:64:20:2:Default:textures/blocks/log_big_oak"
> - "20:0:64:25:2:Default:textures/blocks/glass"
> - "24:0:64:50:2:Default:textures/blocks/sandstone_normal"
> - "98:0:64:50:2:Default:textures/blocks/stonebrick"
> - "155:0:64:75:2:Default:textures/blocks/quartz_block_side"
> - "88:0:64:30:0.5:Default:textures/blocks/snow"
> - "44:0:64:75:3:Default:textures/blocks/stone_slab_side"
> - "47:0:64:50:2:Default:textures/blocks/bookshelf"
> - "45:0:64:50:2:Default:textures/blocks/brick"
> - "87:0:64:150:1:Default:textures/blocks/nether_brick"
> 2:
> Name: "Nourriture:textures/items/apple"
> Items:
> - "466:0:1:18000:0:Default:http://saltypixel.ga/textures/items/enchanted_golden_apple.png"
> - "322:0:1:1500:0:Default:textures/items/apple_golden"
> - "364:0:16:5:1:Default:textures/items/beef_cooked"
> - "320:0:16:6:1:Default:textures/items/porkchop_cooked"
> - "424:0:16:5:1:Default:textures/items/mutton_cooked"
> 3:
> Name: "Agriculture:textures/items/stone_hoe"
> Items:
> - "291:0:1💯1:Default:textures/items/stone_hoe"
> - "351:15:32:50:1.75:Default:/textures/items/inc_sac"
> - "296:0:12:50:2.50:Default:textures/items/seeds_wheat"
> - "338:0:32:50:2:Default:textures/items/sugar_cane"
> - "362:0:32:50:1.50:Default:textures/items/seeds_melon"
> - "360:0:1:10:1:Default:textures/items/melon"
> - "361:0:32:50:2:Default:textures/items/seeds_pumpkin"
> - "391:0:32:50:1:Default:textures/items/carrot"
> - "392:0:32:50:1:Default:textures/items/potato"
> 4:
> Name: "Musique:textures/blocks/jukebox_top"
> Items:
> - "84:0:1:50000:0:Default:textures/blocks/jukebox_top"
> - "501:0:1:5000:0:Skrillex - Bangarang:textures/items/record_cat"
> - "500:0:1:5000:0:Petit biscuit - Sunset Lover:textures/items/record_13"
> - "503:0:1:5000:0:Alan walker - Fade:textures/items/record_chirp"
> - "504:0:1:5000:0:Tobu - Hope:textures/items/record_far"
> - "505:0:1:5000:0:Manuel - GAS GAS GAS:textures/items/record_mall"
> - "506:0:1:5000:0:Default:textures/items/record_mellohi"
> - "507:0:1:5000:0:Default:textures/items/record_stal"
> - "508:0:1:5000:0:Default:textures/items/record_strad"
> - "509:0:1:5000:0:Default:textures/items/record_ward"
> - "510:0:1:5000:0:OMFG - HELLO:textures/items/record_11"
> - "511:0:1:5000:0:Default:textures/items/record_wait"
> 5:
> Name: "Minerais:textures/items/diamond"
> Items:
> - "264:0:1:350:150:Default:textures/items/diamond"
> - "265:0:1:250💯Default:textures/items/iron_ingot"
> - "266:0:1:275:60:Default:textures/items/gold_ingot"
> - "388:0:1:400:200:Default:textures/items/emerald"
> - "263:0:1:25:1.75:Default:textures/items/coal"
> - "351:4:1:25:10:Default:textures/items/lapis_lazuli"
> - "331:0:1:25:5:Default:textures/items/redstone"
> 6:
> Name: "Spawners et Loots:textures/blocks/mob_spawner"
> Items:
> - "52:0:1:1000💯Default:textures/blocks/mob_spawner"
> - "383:34:1:50000💯Default:textures/items/egg_skeleton"
> - "383:35:1:75000💯Default:textures/items/egg_spider"
> - "383:43:1:150000💯Default:textures/items/egg_blaze"
> - "383:36:1:250000💯Default:textures/items/egg_pigzombie"
> - "383:33:1:300000💯Default:textures/items/egg_creeper"
> - "383:20:1:400000💯Default:textures/items/egg"
> - "369:0:64:500:50:Default:textures/items/blaze_rod"
> - "352:0:64:50:3.5:Default:textures/items/bone"
> - "262:0:64:50:2.5:Default:textures/items/arrow"
> - "287:0:64:50:4:Default:textures/items/string"
> - "375:0:64:10:3:Default:textures/items/spider_eye"
> - "371:0:64:50:5:Default:textures/items/gold_nugget"
> - "288:0:64:10:5:Default:textures/items/feather"
> - "334:0:64:10:5:Default:textures/items/leather"
> - "367:0:1:10:10:Default:textures/items/rotten_flesh"
> 7:
> Name: "Argile:textures/blocks/hardened_clay"
> Items:
> - "172:0:64:15:3:Default:textures/blocks/hardened_clay"
> - "159:0:64:20:4:Default:textures/blocks/hardened_clay_stained_white"
> - "159:1:64:20:4:Default:textures/blocks/hardened_clay_stained_orange"
> - "159:2:64:20:4:Default:textures/blocks/hardened_clay_stained_magenta"
> - "159:3:64:20:4:Default:textures/blocks/hardened_clay_stained_light_blue"
> - "159:4:64:20:4:Default:textures/blocks/hardened_clay_stained_yellow"
> - "159:5:64:20:4:Default:textures/blocks/hardened_clay_stained_lime"
> - "159:6:64:20:4:Default:textures/blocks/hardened_clay_stained_pink"
> - "159:7:64:20:4:Default:textures/blocks/hardened_clay_stained_gray"
> - "159:8:64:20:4:Default:textures/blocks/hardened_clay_stained_silver"
> - "159:9:64:20:4:Default:textures/blocks/hardened_clay_stained_cyan"
> - "159:10:64:20:4:Default:textures/blocks/hardened_clay_stained_purple"
> - "159:11:64:20:4:Default:textures/blocks/hardened_clay_stained_blue"
> - "159:12:64:20:4:Default:textures/blocks/hardened_clay_stained_brown"
> - "159:13:64:20:4:Default:textures/blocks/hardened_clay_stained_green"
> - "159:14:64:20:4:Default:textures/blocks/hardened_clay_stained_red"
> - "159:15:64:20:4:Default:textures/blocks/hardened_clay_stained_black"
> 8:
> Name: "Béton:textures/blocks/concrete"
> Items:
> - "237:0:64:20:4:Default:textures/blocks/concrete_powder_white"
> - "237:1:64:20:4:Default:textures/blocks/concrete_powder_orange"
> - "237:2:64:20:4:Default:textures/blocks/concrete_powder_magenta"
> - "237:3:64:20:4:Default:textures/blocks/concrete_powder_light_blue"
> - "237:4:64:20:4:Default:textures/blocks/concrete_powder_yellow"
> - "237:5:64:20:4:Default:textures/blocks/concrete_powder_lime"
> - "237:6:64:20:4:Default:textures/blocks/concrete_powder_pink"
> - "237:7:64:20:4:Default:textures/blocks/concrete_powder_gray"
> - "237:8:64:20:4:Default:textures/blocks/concrete_powder_silver"
> - "237:9:64:20:4:Default:textures/blocks/concrete_powder_cyan"
> - "237:10:64:20:4:Default:textures/blocks/concrete_powder_purple"
> - "237:11:64:20:4:Default:textures/blocks/concrete_powder_blue"
> - "237:12:64:20:4:Default:textures/blocks/concrete_powder_brown"
> - "237:13:64:20:4:Default:textures/blocks/concrete_powder_green"
> - "237:14:64:20:4:Default:textures/blocks/concrete_powder_red"
> - "237:15:64:20:4:Default:textures/blocks/concrete_powder_black"

**Comment by AlexPads** [comment]
@FaanMaario you must have an outside issue the plugin slapper plus and slapper mover disable the forms for other plugins causing issues with the shop this is because those plugins are no longer supported and can cause issues in your server try removing any other shop plugins and slapper plus or slapper movement if installed.


that might help but if not could you please explain more?

**Comment by LeoBdt** [comment]
We don't have slapper plus

**Comment by LeoBdt** [comment]
And slapper mover don't use forms

**Comment by LeoBdt** [comment]
And the error is when we tried to buy something, it just close the window and saying "thanks for purchase" without giving the items. But it's working for buying commands.

**Comment by AlexPads** [comment]
Try changing the item to something you 100% know the item I'd to. and
change things because I use this exact version on my servers and don't have
this problem are you using the latest version?

**Comment by LeoBdt** [comment]
Yes we're using the latest version and all of id are corrects.

**Comment by AlexPads** [comment]
Its interference with another plugin the only way to fix it is to remove plugins one by one and figure out what one is causing it report it to me and i can patch it.

**Comment by AlexPads** [comment]
@LeoBdt This has never happened before and it just seems like you might have something set up wrong.
