### ISSUE TITLE
Server Internal Erro

### ISSUE THREAD

**Issue by alallalalalallalal** [AlexPads/ShopUI-FormAPI-Working#30]
Mar 24 07:22 [Server] Server thread/DEBUG #19 (9): include(string phar:///jar/pocketmine/pmmp/1.10.0-3.7.0/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
Mar 24 07:22 [Server] Server thread/DEBUG #18 src/pocketmine/PocketMine(250): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
Mar 24 07:22 [Server] Server thread/DEBUG #17 src/pocketmine/Server(1766): pocketmine\Server->start()
Mar 24 07:22 [Server] Server thread/DEBUG #16 src/pocketmine/Server(2187): pocketmine\Server->tickProcessor()
Mar 24 07:22 [Server] Server thread/DEBUG #15 src/pocketmine/Server(2329): pocketmine\snooze\SleeperHandler->sleepUntil(double 1553433743.4382)
Mar 24 07:22 [Server] Server thread/DEBUG #14 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
Mar 24 07:22 [Server] Server thread/DEBUG #13 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
Mar 24 07:22 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/RakLibInterface(100): pocketmine\network\mcpe\RakLibInterface->process()
Mar 24 07:22 [Server] Server thread/DEBUG #11 src/pocketmine/network/mcpe/RakLibInterface(110): raklib\server\ServerHandler->handlePacket()
Mar 24 07:22 [Server] Server thread/DEBUG #10 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 188.154.139.97 57789, raklib\protocol\EncapsulatedPacket object, integer 0)
Mar 24 07:22 [Server] Server thread/DEBUG #9 src/pocketmine/network/mcpe/RakLibInterface(170): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
Mar 24 07:22 [Server] Server thread/DEBUG #8 src/pocketmine/Player(3113): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
Mar 24 07:22 [Server] Server thread/DEBUG #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
Mar 24 07:22 [Server] Server thread/DEBUG #6 src/pocketmine/network/mcpe/protocol/BatchPacket(119): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\ModalFormResponsePacket object)
Mar 24 07:22 [Server] Server thread/DEBUG #5 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\ModalFormResponsePacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
Mar 24 07:22 [Server] Server thread/DEBUG #4 src/pocketmine/network/mcpe/protocol/ModalFormResponsePacket(49): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleModalFormResponse(pocketmine\network\mcpe\protocol\ModalFormResponsePacket object)
Mar 24 07:22 [Server] Server thread/DEBUG #3 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(259): pocketmine\Player->onFormSubmit(integer 5, array Array())
Mar 24 07:22 [Server] Server thread/DEBUG #2 src/pocketmine/Player(3449): SaltyPixelDevz\CustomShopUIv2\libs\jojoe77777\FormAPI\Form->handleResponse(pocketmine\Player object, array Array())
Mar 24 07:22 [Server] Server thread/DEBUG #1 plugins/ShopUI-FormAPI-Working.phar/src/SaltyPixelDevz/CustomShopUIv2/libs/jojoe77777/FormAPI/Form(46): SaltyPixelDevz\CustomShopUIv2\Shop->SaltyPixelDevz\CustomShopUIv2\{closure}(pocketmine\Player object, array Array())
Mar 24 07:22 [Server] Server thread/DEBUG #0 plugins/ShopUI-FormAPI-Working.phar/src/SaltyPixelDevz/CustomShopUIv2/Shop(298): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string Undefined offset: 3, string phar:///plugins/ShopUI-FormAPI-Working.phar/src/SaltyPixelDevz/CustomShopUIv2/Shop.php, integer 298, array Array())
Mar 24 07:22 [Server] Server thread/CRITICAL ErrorException: "Undefined offset: 3" (EXCEPTION) in "plugins/ShopUI-FormAPI-Working.phar/src/SaltyPixelDevz/CustomShopUIv2/Shop" at line 298

**Comment by AlexPads** [comment]
when did this happen? do you have FormAPI installed like it says to?

**Comment by AlexPads** [comment]
not formAPI EconomyAPI

**Comment by alallalalalallalal** [comment]
i have all that (formapi and economyAPI)

**Comment by AlexPads** [comment]
When did you get that error and how do you know it's related to my plugin ?
Have you saved a copy of your shop.yml and config and messages.yml files
and moved them to another folder and restarted the plug-in to get a new
file to make sure it works?

**Comment by AlexPads** [comment]
integer 8, string Undefined offset: 3, string phar:///plugins/ShopUI-FormAPI-Working.phar/src/SaltyPixelDevz/CustomShopUIv2/Shop.php, integer 298, array Array())
Mar 24 07:22 [Server] Server thread/CRITICAL ErrorException: "Undefined offset: 3" (EXCEPTION) in "plugins/ShopUI-FormAPI-Working.phar/src/SaltyPixelDevz/CustomShopUIv2/Shop" at line 298

That there is saying that you have something wrong in your config file I would suggest putting your config into a YAML validator on the internet and having it check for missing items.

**Comment by AlexPads** [comment]
Solved in 4.0.0
