### ISSUE TITLE
Missing button back in the store

### ISSUE THREAD

**Issue by n1k1ta99s** [AlexPads/ShopUI-FormAPI-Working#32]
Missing button back in the store

**Comment by AlexPads** [comment]
You can enable it in the config file

**Comment by n1k1ta99s** [comment]
@AlexPads 
included in config file but not working

**Comment by AlexPads** [comment]
Alright I'll fix it

**Comment by AlexPads** [comment]
The Exit Buttons and Back Buttons all work in version 4.0.1 so im not sure what your issue is.
