### ISSUE TITLE
Share your Plugin

### ISSUE THREAD

**Issue by SonsaYT04** [AlexPads/ShopUI-FormAPI-Working#37]
Hello, I'm inviting you to join and share your free plugin to our website. You have options to make short download link to earn. We want to help developers to earn by making free plugin. https://www.mcbe.tk/plugins

**Comment by AlexPads** [comment]
Didn't you work at HappyBe before they made a Mistake and Merged with ScamNetwork "NG"
And yeah ill share on there once I Look at the website im at school Right Now and it's blocked here.
@SonsaYT04

**Comment by SonsaYT04** [comment]
Yes. Thanks :D

**Comment by AlexPads** [comment]
@SonsaYT04 Would you consider Helping me with my server or no. It's fine if you don't want to. and I didn't get a chance to post on there yesterday I will do it when I have time.
Thank You!

**Comment by AlexPads** [comment]
@SonsaYT04 Plugin has been shared :)
