### ISSUE TITLE
Line 86

### ISSUE THREAD

**Issue by ZZWILLIAMXXTrue** [AlexPads/ShopUI-FormAPI-Working#39]
When I do /shop it crashes the player.
![AAE8E0F3-8E0B-4ED2-96BE-1479D961DED8](https://user-images.githubusercontent.com/49970753/61029651-24802f80-a381-11e9-9a4a-ae6baf40a6b7.png)
![6B1E8B49-692E-49D3-B27E-54E08FFD8693](https://user-images.githubusercontent.com/49970753/61029652-24802f80-a381-11e9-86a4-c38e56b6f968.png)
![886CDB97-FBF6-4ACB-A493-67D3A48BDFE9](https://user-images.githubusercontent.com/49970753/61029655-24802f80-a381-11e9-82e0-5f28a2e26c93.png)

**Comment by AlexPads** [comment]
Something on your shop.yml is setup wrong.

**Comment by ZZWILLIAMXXTrue** [comment]
Ok I fixed it!
