### ISSUE TITLE
Give command 

### ISSUE THREAD

**Issue by PlutoZetaptor** [AlexPads/ShopUI-FormAPI-Working#40]
Hi dude one question. I want too add a command that gives a key from the plugin mysterycrate. I tryed - "cmd:test:100:Console:give {player} vote 1:textures/items/paper"

But it didnt work

Ok and 2 question. What is the permissions for /shop vip? I want that only vip can use it.

**Comment by AlexPads** [comment]
Well that command should work not sure what happened there...

And it should be permission shop.vip

**Comment by AlexPads** [comment]
Alexpads#9162

**Comment by PlutoZetaptor** [comment]
Ok I send u a invite :)

**Comment by AlexPads** [comment]
sry send again I forgot and ejected it 😂
