### ISSUE TITLE
weird bug

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [AlexPads/ShopUI-FormAPI-Working#41]
It seems that item number is show as sell price in diamonds and other ores.
For example, diamonds are 80 but in menu it show 12.

**Comment by TDMidkwhatisxd** [comment]
So confusing, i was thinking that number is how many items/price ohhhh, or how many items  per transaction

**Comment by benda95280** [comment]
I've take a close look in the source code, it seems it's not used elsewhere than in the form (UI) ...

**Comment by benda95280** [comment]
I've been able to implement the necessary modification to have good information showed and item in inventory on my side.
Don't know how to PR it ...

**Comment by AlexPads** [comment]
Yes the plugin is still maintained........
WHAT IS THE ISSUE WHY CANT ANYONE EXPLAIN WHEN I ASK THEM TO. I need details versions..... Anything....

**Comment by benda95280** [comment]
Dear Alex,

Sorry about that.
I've try with the last version, problem is present.

If you take a closer look in shop.php, you will find that the "Number" is used in form, but not in calc.

**Comment by AlexPads** [comment]
Could you submit a pull request so I could better understand the issue?

**Comment by benda95280** [comment]
Take a look here:
https://github.com/AlexPads/ShopUI-FormAPI-Working/compare/master...benda95280:master

Sorry, my first time using GitHub, but take a look on line 225 and 445 (and above)
_I've removed some permission, because was not able to use it as i want :(_
