### ISSUE TITLE
Help !

### ISSUE THREAD

**Issue by LamPocketVN** [AlexPads/ShopUI-FormAPI-Working#42]
![Minecraft 7_18_2019 1_56_45 PM_LI](https://user-images.githubusercontent.com/33188123/61436029-18d5cf80-a964-11e9-90b2-fbe47768a002.jpg)
Can you fix this ??

**Comment by AlexPads** [comment]
Are you sure you are on the latest version?

**Comment by TDMidkwhatisxd** [comment]
Alex can you tell me what is the item number? It appear as price and does not seems to affect anything

**Comment by TDMidkwhatisxd** [comment]
To show the correct price i show item number same as item price, but im afraid that players to not get like 50 stuff for 50 and sell for like 25 each xd

**Comment by LamPocketVN** [comment]
Yes I am in lastest version !

**Comment by AlexPads** [comment]
I am very confused on what your problem is..... Do you have anyways to to
explain better ?

**Comment by AlexPads** [comment]
If it is doing that in your shop than you have configured something incorrectly.
