### ISSUE TITLE
no purchase / sale possible!

### ISSUE THREAD

**Issue by StrawberryNature** [AlexPads/ShopUI-FormAPI-Working#44]
Really good plugin i love it.  now I have two days the problem, if one has selected his item and want to buy that no money is deducted and thus no items is placed in the inventory.  get the nice text "many dnk for the use of the shop" to see and that was it but also ... a great pity please help, I would like to continue to use the plugin.

**Comment by AlexPads** [comment]
Do you have economy API installed? Was the plugin working before? What other UI plugins have you installed scince than.

**Comment by StrawberryNature** [comment]
yes and formapi too, it worked until two days ago.
I also use GamemodeUI, EconomyJobUI, EacTableU and ReportUI

**Comment by AlexPads** [comment]
Do all those other plugins work still.

**Comment by StrawberryNature** [comment]
ja alle einwandfrei

**Comment by AlexPads** [comment]
so you're just saying that the plugin does not work at all? are you sure that you don't have something set up wrong?

**Comment by StrawberryNature** [comment]
exactly.  I have not touched the config, where the update for Poketmine came out to go to the 1.12

**Comment by AlexPads** [comment]
I just installed the plug-in on a blank install of the latest pmmp and it worked with no issues. You must have a conflict from another plugin.

**Comment by StrawberryNature** [comment]
sorry for the premature closing of this problem, have now recognized the problem it is due to the translation in German.  have probably done something wrong because in the original condition I can buy and get the items in my not.  great plugin will find my problem sometime.
