### ISSUE TITLE
/shop Wont work

### ISSUE THREAD

**Issue by ZZWILLIAMXXTrue** [AlexPads/ShopUI-FormAPI-Working#45]
20.09 12:20:30 [Server] Server thread/CRITICAL ErrorException: "yaml_parse(): parsing error encountered during parsing: did not find expected key (line 77, column 3), context while parsing a block mapping (line 2, column 1)" (EXCEPTION) in "src/pocketmine/utils/Config" at line 181
20.09 12:20:30 [Server] Server thread/DEBUG #0 (): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string[159] yaml_parse(): parsing error encountered during parsing: did not find expected ke, string[116] phar:///PMMP-1.12.0-Latest-Stable., integer 181, array[4])
20.09 12:20:30 [Server] Server thread/DEBUG #1 src/pocketmine/utils/Config(181): yaml_parse(string[5263] # DO NOT TOUCH (This is for Updates only!)..shop-version: 4..# DO NOT TOUCH ^^^^)
20.09 12:20:30 [Server] Server thread/DEBUG #2 src/pocketmine/utils/Config(113): pocketmine\utils\Config->load(string[80] /plugin_data/CustomShopUI/shop.yml, integer 2, array[0])
20.09 12:20:30 [Server] Server thread/DEBUG #3 plugins/ShopUI-FormAPI-Working.phar/src/SaltyPixelDevz/CustomShopUIv2/Shop(56): pocketmine\utils\Config->__construct(string[80] /plugin_data/CustomShopUI/shop.yml, integer 2)
20.09 12:20:30 [Server] Server thread/DEBUG #4 plugins/ShopUI-FormAPI-Working.phar/src/SaltyPixelDevz/CustomShopUIv2/Shop(46): SaltyPixelDevz\CustomShopUIv2\Shop->checkConfigs()
20.09 12:20:30 [Server] Server thread/DEBUG #5 src/pocketmine/plugin/PluginBase(123): SaltyPixelDevz\CustomShopUIv2\Shop->onEnable()
20.09 12:20:30 [Server] Server thread/DEBUG #6 src/pocketmine/plugin/PluginManager(580): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
20.09 12:20:30 [Server] Server thread/DEBUG #7 src/pocketmine/Server(2002): pocketmine\plugin\PluginManager->enablePlugin(object SaltyPixelDevz\CustomShopUIv2\Shop)
20.09 12:20:30 [Server] Server thread/DEBUG #8 src/pocketmine/Server(1988): pocketmine\Server->enablePlugin(object SaltyPixelDevz\CustomShopUIv2\Shop)
20.09 12:20:30 [Server] Server thread/DEBUG #9 src/pocketmine/Server(1782): pocketmine\Server->enablePlugins(integer 1)
20.09 12:20:30 [Server] Server thread/DEBUG #10 src/pocketmine/PocketMine(275): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[47] /, string[55] /plugins/)
20.09 12:20:30 [Server] Server thread/DEBUG #11 src/pocketmine/PocketMine(299): pocketmine\server()
20.09 12:20:30 [Server] Server thread/DEBUG #12 (1): require(string[114] phar:///PMMP-1.12.0-Latest-Stable.)

**Comment by AlexPads** [comment]
That means that you have an error in one of your config files please make
sure that you have edited them properly! If you can't find it send me a
copy I can help!!

**Comment by ZZWILLIAMXXTrue** [comment]
Ok

**Comment by ZZWILLIAMXXTrue** [comment]
Config:
# DO NOT TO
config-version: 5
# DO NOT TOUCH^^^^

# When someone closes the shop it shuts completely out they will have to run the command again!
Straight_Back: false

# when someone closes the shop it goes back to the Category area they can then close it from there.
Back_to_Start: false

# This makes the Command only work when the player is in Survival
Survival: false

# This is Used to Ban Commands in only the Worlds Below.
Worlds: ["bannedworld1", "bannedworld2"] # You can add as Many as needed

# This adds an Exit Button to Categories Section of Plugin (Recommended to Leave false)
Category_ExitButton: true
Items_ExitButton: true

# Turns off Messages like Thanks for Using On Close!
Thanks: true

#Turns on or off the Command Confirmation Window
command_confirm: true

# Turns on or off Multi Shop Support!
Multi-Shop: true

# Default Shop for when the Player Runs the /shop command with no Arguments!
Default-Shop: "Shop"
Titles:
  # adding these is simple just put exactly what you have in the shop.yml as the name and then title after it and then the name!
  Default: "ShopUI" ## This is default for when you don't add the titles Below!
  shoptitle: "ShopUI"



Types:
  Toggle: true #it is NOT recommended to change this! (Changing this means the Plugin wont work This will be Fixed in a few updates!)
  Input: false # true or false (adds Number input player has to type)
  Slider: true # true or false (adds slider Input Player has to Slide the Slider)
  Slider_Minimum: 1 # Must be a Number (Number for Normal Slider)
  Slider_Maximum: 128 # Must be a Number (Number for Maximum Amount they can Buy)
  StepSlider: true # true or false (adds step Slider)
  Slider_Numbers: ["1", "16", "32", "64", "128"] # You can add more Numbers if you follow the Same format!
Shop Config:
# DO NOT TOUCH (This is for Updates only!)
shop-version: 4
# DO NOT TOUCH ^^^^^

#Command Example!!!
#======================================================================================================
# Commands:
#
#
#    - "cmd:Sharpness III:100:Console:enchant {player} protection 3:textures/items/stone_sword"
#            NAME^^^ Price^^^ TYPE^^^            COMMAND^^^^^             PICTURE^^^^^^^
#
# Items:
#
#   - "268:0:1:250:0:Default:textures/items/wood_sword"
#
#   - "ID:META:NUMBER:PRICE(PER ITEM THEY BUY):SELL(PER ITEM THEY SELL):NAME(Defalut OR Custom with Â§):Picture"
#
######## IMPORTANT #########
#
#  Next Update Finishes Enchants (Can be Done with Commands!)
#
#  NEW!!! We have a Minecraft Texture Library on our Website!
#         Go to: http://saltypixel.gs/textures after that add the item like this:
#                   http://saltypixel.ga/textures/blocks/tnt_side.png (You can Send us .png files and we will add them!)
#                          That would Look like this in use!
#
#   - "268:0:1:250:0:Default:http://saltypixel.ha/textures/blocks/tnt_side.png"
#
#
# Developer: AlexPads Team: SaltyPixelDevz! (hub.saltypixel.ga 19132) Join!
# NEW!!!!!!!!!! SubCategories!
#======================================================================================================

# MUST be all Lowercase! RECOMMENDED TO KEEP THIS YOUR DEFAULT SHOP!
shop: # if you want the shop to have a custom name you must add the options in the Config.yml file if now it will default to ShopUI
  0: #must start at 0 and go up by one with every new category you make.
    Name: "Biome Items:textures/blocks/netherrack" #Can use Custom Colors in the Names using the "Â§" Symbol
    Sub:
      0:
        Name: "Nether:textures/blocks/netherrack"
        Items:
          - "87:0:1000:1000:500:Default:textures/blocks/netherrack"
          - "89:0:2500:2500:1250:Default:textures/blocks/glowstone"
          - "406:0:5000:5000:2500:Default:textures/items/quartz"
          - "88:0:7500:7500:3750:Default:textures/blocks/soul_sand"
          - "213:0:7500:7500:3750:Default:textures/blocks/magma"
          - "397:1:10000:10000:10000:Default:textures/entity/skeleton/wither_skeleton"
      1:
        Name: "End:textures/blocks/end_stone"
        Items:
          - "121:0:2000:2000:1000:Default:textures/blocks/end_stone"
          - "206:0:4000:4000:2000:Default:textures/blocks/end_bricks"
          - "201:0:5000:5000:2500:Default:textures/blocks/purpur_block"
          - "368:0:8000:8000:4000:Default:textures/blocks/ender_pearl"
          - "397:5:100000:100000:50000:Default:textures/entity/enderdragon/dragon"
      2:
        Name: "Sea:textures/blocks/prismarine"
        Items:
          - "337:0:500:500:250:Default:textures/items/clay"
          - "168:0:1000:1000:500:Default:textures/blocks/prismarine"
          - "168:2:2500:2500:1250:Default:textures/blocks/prismarine_bricks"
          - "168:1:5000:5000:2500:Default:textures/blocks/dark_prismarine"
          - "169:0:10000:10000:5000:Default:textures/blocks/sea_lantern"
      3:
        Name: "Snow:textures/blocks/snow"
        Items:
          - "332:0:500:500:250:Default:textures/items/snowball"
          - "80:0:1000:1000:500:Default:textures/items/snow"
          - "79:0:2000:2000:1000:Default:textures/items/ice"
1:
    Name: "Food & Gapples:textures/items/carrot_golden"
    Items:
      - "466:0:1000000:1000000:500000:Default:textures/items/enchanted_golden_apple"
      - "322:0:10000:10000:5000:Default:textures/items/apple_golden"
      - "396:0:5000:5000:2500:Default:textures/items/carrot_golden"
  2:
    Name: "Farming:textures/items/stone_hoe"
    Items:
      - "296:0:100:100:50:Default:textures/items/seeds_wheat"
      - "338:0:100:100:50:Default:textures/items/sugar"
      - "362:0:100:100:50:Default:textures/items/seeds_melon"
      - "361:0:100:100:50:Default:textures/items/seeds_pumpkin"
      - "391:0:100:100:50:Default:textures/items/carrot"
      - "392:0:100:100:50:Default:textures/items/potato"
  3: 
    Name: "Saplings:textures/items/sapling"
    Items:
      - "6:0:100:100:50:Default:textures/items/sapling"
      - "6:1:200:200:100:Default:textures/items/sapling"
      - "6:2:200:200:100:Default:textures/items/sapling"
      - "6:3:200:200:100:Default:textures/items/sapling"
      - "6:4:200:200:100:Default:textures/items/sapling"
      - "6:5:200:200:100:Default:textures/items/sapling"
  4:
    Name: "Mob Drops:textures/items/bone"
    Items:
      - "352:0:5000:5000:2500:Default:textures/items/bone"
      - "334:0:5000:5000:2500:Default:textures/items/leather"
      - "288:0:5000:5000:2500:Default:textures/items/feather"
  5:
    Name: "Ores:textures/items/diamond"
    Items:
      - "263:0:500:500:250:Default:textures/items/coal"
      - "265:0:1000:1000:500:Default:textures/items/iron_ingot"
      - "266:0:2000:2000:1000:Default:textures/items/gold_ingot"
      - "351:4:4000:4000:2000:Default:textures/items/dye"
      - "331:0:4000:4000:2000:Default:textures/items/redstone"
      - "264:0:8000:8000:4000:Default:textures/items/diamond"
      - "388:0:10000:10000:5000:Default:textures/items/emerald"
...

**Comment by ZZWILLIAMXXTrue** [comment]
Idk why there are 💯 and big letters, it looks normal in the config

**Comment by AlexPads** [comment]
Can you please use a site like pastebin or hastebin thanks 👍

**Comment by ZZWILLIAMXXTrue** [comment]
https://pastebin.com/wjLWG98Y

**Comment by ZZWILLIAMXXTrue** [comment]
Found out the problem, for some reason ramshard is really messed up with spaces.

**Comment by AlexPads** [comment]
Yeah I was going to say that your config has some messed up spaces.
