### ISSUE TITLE
How to sell commands

### ISSUE THREAD

**Issue by MisledPaul58** [AlexPads/ShopUI-FormAPI-Working#50]
Hi, this plugin is really cool, but I want to sell commands, how can I do it?

**Comment by ZZWILLIAMXXTrue** [comment]
If you have PurePerms just do /setuperms {PLAYER} (permission for a command)

**Comment by MisledPaul58** [comment]
> If you have PurePerms just do /setuperms {PLAYER} (permission for a command)

But I want to sell them for a price.

**Comment by Johnsonk79** [comment]
read config dude

**Comment by AlexPads** [comment]
It tells you exactly how in the top of the shop.yml file.

**Comment by MisledPaul58** [comment]
Where
## DO NOT TOUCH (This is for Updates only!)
shop-version: 4
# DO NOT TOUCH ^^^^^

#Command Example!!!
#======================================================================================================
# Commands:
#
#
#    - "cmd:Sharpness III:100:Console:enchant {player} protection 3:textures/items/stone_sword"
#            NAME^^^ Price^^^ TYPE^^^            COMMAND^^^^^             PICTURE^^^^^^^
#
# Items:
#
#   - "268:0:1:250:0:Default:textures/items/wood_sword"
#
#   - "ID:META:NUMBER:PRICE(PER ITEM THEY BUY):SELL(PER ITEM THEY SELL):NAME(Defalut OR Custom with §):Picture"
#
######## IMPORTANT #########
#
#  Next Update Finishes Enchants (Can be Done with Commands!)
#
#  NEW!!! We have a Minecraft Texture Library on our Website!
#         Go to: http://saltypixel.gs/textures after that add the item like this:
#                   http://saltypixel.ga/textures/blocks/tnt_side.png (You can Send us .png files and we will add them!)
#                          That would Look like this in use!
#
#   - "268:0:1:250:0:Default:http://saltypixel.ha/textures/blocks/tnt_side.png"
#
#
# Developer: AlexPads Team: SaltyPixelDevz! (hub.saltypixel.ga 19132) Join!
# NEW!!!!!!!!!! SubCategories!

**Comment by AlexPads** [comment]
`- "cmd:Sharpness III:100:Console:enchant {player} protection 3:textures/items/stone_sword"`

Just add that as an Item and it will run whatever command you set it to...
