### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by mrpwes** [AlexPads/ShopUI-FormAPI-Working#55]
Is it possible to retrieve the image locally ?

**Comment by AlexPads** [comment]
Yes, just use a local path to a image file

**Comment by mrpwes** [comment]
Name: "Redstone Stuff:/root/img/enchantedstick.png"

![image](https://user-images.githubusercontent.com/31194909/82808345-698b5280-9ebc-11ea-8ae3-f955be0cb4c6.png)

not working :< idk what is my error

**Comment by mrpwes** [comment]
im using linux

**Comment by mrpwes** [comment]
how to retrieve the image locally ?

**Comment by mrpwes** [comment]
not working i tried lots of shits im sucks
![image](https://user-images.githubusercontent.com/31194909/88882540-c9a7c780-d264-11ea-93de-73cc7446ec78.png)
