### ISSUE TITLE
VIP SHOP Permission

### ISSUE THREAD

**Issue by foxysy** [AlexPads/ShopUI-FormAPI-Working#61]

**Comment by foxysy** [comment]
need the vip shop permission, in the plugin file it only say about the shop.shop of the normal /shop but nothing about vip shop.
if i get op the command work without problems. when i try to see all the perms with hierarchy plugin i can see only shop.shop and other 254 permissions, so can anyone tell me what is the true perm for this? ty

**Comment by AlexPads** [comment]
shop.shopname
