### ISSUE TITLE
server crash. when i hit button on shop ui.

### ISSUE THREAD

**Issue by LeoBdt** [AlexPads/ShopUI-FormAPI-Working#7]
![capture d ecran du 2018-12-19 19 51 50](https://user-images.githubusercontent.com/11062780/50241360-941fd480-03c7-11e9-806a-9b6fc29555ec.png)

**Comment by AlexPads** [comment]
Can I please have more information like:
OS
Plugin Version
pmmp version
php version
stuff lie that what specific button you pressed?
Thanks when I can I will look at line 94

**Comment by LeoBdt** [comment]
OS : debian 9.1
plugin version : 3.0.1
pmmp version : 3.5.1 
php version : the last ?? 
every button make the error.

**Comment by AlexPads** [comment]
should be fixed when poggit approves 3.0.2 :) Thanks!!!!!!!!

**Comment by LeoBdt** [comment]
btw can we talk on twitter or discord please ? it's very important

**Comment by AlexPads** [comment]
yes ill add u when I get home
