### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Tuvqlu** [AlexPads/ShopUI-FormAPI-Working#76]
Hi it crashes when I type /shop, it says this:

![image](https://user-images.githubusercontent.com/98550458/154809339-95c0912b-331a-44ed-be7a-1923796060cc.jpeg)

I have formapi dev 5
And FormsUI by Vecna
Help

**Comment by AlexPads** [comment]
I am looking into it. Looks like the Viron has not been successfully initiated by Poggit.

**Comment by AlexPads** [comment]
This is resolved in the latest dev version [here](https://poggit.pmmp.io/r/162683/ShopUI-FormAPI-Working_dev-85.phar).
