### ISSUE TITLE
i can't buy ! :/

### ISSUE THREAD

**Issue by LeoBdt** [AlexPads/ShopUI-FormAPI-Working#8]
OS : debian 9.1
plugin version : 3.0.2 (your """fix""")
pmmp version : 3.5.1
php version : the last ??

ok so now if i hit a button (for exemple blocks) it will just say "Thanks for using ShopUi" in tchat, and do nothing else

**Comment by AlexPads** [comment]
Well please go back to 3.0.0 as i obviously have 2 not good versions rn -_- i am coming out with a complete rewrite in a few days that will be 100% tested and Hopefully Fully working These last two builds have been slowly me putting things in but as you can see it is not working Thank you for the Report with the inaccurate php version.

**Comment by AlexPads** [comment]
Download the latest commit from poggit dev section i think its 37 just download the top one and see if that fixes it 
Thanks

**Comment by LeoBdt** [comment]
nice, please could you add me on discord ? Léo#0032 

i need you to help me to fix my NoRegen plugin.....

**Comment by LeoBdt** [comment]
btw are your french?

**Comment by AlexPads** [comment]
ill add you later and no im not French im German but I live in the USA xD
