### ISSUE TITLE
same error... again and again ....

### ISSUE THREAD

**Issue by LeoBdt** [AlexPads/ShopUI-FormAPI-Working#9]
OS : debian 9.1
plugin version : 3.0.3 (your """fix""")
pmmp version : 3.5.1
php version : the last ??

ok so now if i hit a button (for exemple blocks) it will just say "Thanks for using ShopUi" in tchat, and do nothing else

**Comment by AlexPads** [comment]
OK Please just go back to 3.0.0 because obviously something is wrong with
the way that the poggit virons are affecting the plugin

**Comment by AlexPads** [comment]
and you getting all snobby like that isn't making want to help you also im
still in high school and its finals week so fixing the plugin is not high
on the todo list

**Comment by LeoBdt** [comment]
i'm sorry i don't want to offens you
